version: "3.3"

services:
  database:
    image: mariadb:10
    container_name: database-nodeca
    restart: always
    environment:
      MYSQL_DATABASE: nodeca
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./init/csv:/var/lib/csv
      - ./init:/docker-entrypoint-initdb.d/:ro
